config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root 'rooms#index'
  resources :rooms do
    resources :messages
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'user/:id', to: 'users#show', as: 'user'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  belongs_to :user

  validates :name, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: %i[ show edit update destroy ]
  
 after_action :set_status, if: :user_signed_in?




  def index
    @rooms = Room.all
    current_user.update(status: "offline") if current_user
  end
  
  def show
    @new_message = Message.new(room: @room, user: current_user)
  end

  def new
    @room = Room.new
    
  end

  def create
    @room = Room.new(rooms_params)
    if @room.save
      redirect_to root_path
    end
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def rooms_params
    params.require(:room).permit(:name).merge(user_id: current_user.id)
  end

  def set_status
    current_user.update(status: "online") if current_user    
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, url: rooms_path, method: :post) do |form| %>
  <%= form.text_field :name, class: 'form-control' %>
  <%= form.submit 'New Room', class: 'btn bg-blue-500 btn-primary mt-2' %>
<% end %>

app/views/rooms/index.html.erb
<h1>Room to wrist lock
</h1>

<h5>
  Logged in as: 
  <%= current_user.email  %>
</h5>

<div class="container-fluid">
  <div class="row">
    <div class="col-3">
      <div>
        <%= render 'form', room: Room.new%>
      </div>
      <div class='mt-3'>
     <% @rooms.each do |room| %>
          <div class="card" >
          <div class="card-body" > 
            
            <%= link_to room.name , room, class: 'room' %>

          </div>
        </div>
    <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<%= turbo_stream_from @room %>

<div id="user-id" data-user-id="<%= current_user.id  %>"></div>
<div id="room-id" data-room-id="<%= @room.id %>"></div>

<h5>
  Logged in as: 
  <%= current_user.email  %>
</h5>

<h1>
  <%= @room.name %>
</h1>





<%= turbo_frame_tag 'new_message' do %>
  <%= form_with(model: [@room, @new_message], remote:true, data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset"})  do |form| %>

  <div id="messages", class="border p-4 rounded-lg overflow-y-scroll", data-controller ="scroll">
    
    <%= render @room.messages %>
  </div>
   <div>
      <%= form.text_field :content, :class => "form-control", :placeholder => "Aa" %>
  </div>

    <div class="send">
     
      
  <div>
    <%= form.submit 'Send', id: 'submit', :class => "bg-blue-500 btn btn-primary" %> 
  </div>
    </div>
  <% end %>
<% end %>




<div class="back">
  <%= link_to 'Back', root_path, :class => "btn btn-secondary" %>
</div>